"use client";

import { useEffect, useState } from "react";
import { AnimatedPageTitle, AnimatedSectionHeading } from "@/components/marketing/animated-page-title";
import { MarketingFooter, MarketingHeroBanner } from "@/components/marketing/site-chrome";
import { CONTACT_EMAIL } from "@/lib/branding";

const contactEmail = CONTACT_EMAIL ?? "your Grant deployment operator";

type TermsSection = {
  id: string;
  title: string;
  paragraphs?: string[];
  bullets?: string[];
  note?: string;
};

const introParagraphs = [
  "These Terms of Service govern your use of Grant. By using Grant, you agree to these Terms. If you do not agree, do not use the service.",
];

const sections: TermsSection[] = [
  {
    id: "scope",
    title: "1. Who these Terms apply to",
    paragraphs: [
      "These Terms apply to anyone who accesses or uses Grant.",
    ],
  },
  {
    id: "about",
    title: "2. About Grant",
    paragraphs: [
      "Grant is a software product that helps users create, manage, and share a canonical context profile across connected AI agents and tools.",
      "Grant may include features such as onboarding, file editing, connected-agent access, proposal review, activity history, and integrations with third-party services.",
    ],
  },
  {
    id: "account",
    title: "3. Your account",
    paragraphs: [
      "You may need to sign in to use Grant.",
      "You are responsible for:",
    ],
    bullets: [
      "keeping your account secure",
      "keeping your login details and access methods private",
      "all activity that happens under your account",
    ],
    note: `If you believe your account has been accessed without permission, contact ${contactEmail}.`,
  },
  {
    id: "content",
    title: "4. Your content",
    paragraphs: [
      "You keep ownership of the content you create, upload, or store in Grant, including your Grant profile, onboarding answers, edits, proposals, and related content.",
      "You give Grant a limited right to host, process, store, transmit, and display that content only as needed to operate and improve the service for you.",
      "This does not give Grant ownership of your content.",
    ],
  },
  {
    id: "agent-generated",
    title: "5. Agent-generated changes",
    paragraphs: [
      "Grant may allow connected agents to read your Grant profile and suggest or submit updates.",
      "You are responsible for deciding whether to accept, reject, or rely on agent-generated content or changes.",
      "Grant is not responsible for incorrect, incomplete, misleading, or unwanted outputs generated by connected agents or third-party AI systems.",
    ],
  },
  {
    id: "commercial-use",
    title: "6. Commercial use",
    paragraphs: ["You may use Grant for personal or commercial work."],
  },
  {
    id: "third-party",
    title: "7. Third-party services",
    paragraphs: [
      "Grant relies on third-party services to operate parts of the product, including services for hosting, authentication, and AI processing.",
      "Grant is not responsible for outages, errors, or changes caused by third-party providers.",
      "Your use of those services may also be subject to their own terms and policies.",
    ],
  },
  {
    id: "availability",
    title: "8. Availability and changes",
    paragraphs: [
      "Grant is provided on an “as is” and “as available” basis.",
      "Grant may change, improve, suspend, or remove features at any time.",
      "No guarantee is made that the service will always be available, uninterrupted, secure, or error-free.",
    ],
  },
  {
    id: "termination",
    title: "9. Suspension and termination",
    paragraphs: [
      "Grant may suspend or terminate access to the service if:",
    ],
    bullets: [
      "these Terms are breached",
      "use of the service creates risk, harm, or legal exposure",
      "the service is being misused in a way that affects Grant or other users",
    ],
    note:
      "You may stop using Grant at any time. If your account is terminated or deleted, some information may be retained where reasonably necessary for legal, operational, fraud-prevention, or record-keeping purposes.",
  },
  {
    id: "privacy",
    title: "11. Privacy",
    paragraphs: [
      "Your use of Grant is also governed by the Privacy Policy.",
      "Please read the Privacy Policy to understand how Grant collects, uses, and stores personal information.",
    ],
  },
  {
    id: "liability",
    title: "12. Liability",
    paragraphs: [
      "To the fullest extent allowed by law, Grant is not liable for any indirect, incidental, special, consequential, or loss-of-profit damages arising from or related to your use of the service.",
      "Grant is also not liable for:",
    ],
    bullets: [
      "loss caused by agent-generated errors",
      "loss caused by third-party service outages",
      "loss caused by your own acceptance or use of generated updates",
      "loss of business, revenue, profits, data, goodwill, or opportunity",
    ],
    note: "Nothing in these Terms excludes or limits liability where it would be unlawful to do so.",
  },
  {
    id: "changes",
    title: "13. Changes to these Terms",
    paragraphs: [
      "Grant may update these Terms from time to time.",
      "If the Terms are updated, the revised version will be posted on this page.",
      "By continuing to use Grant after changes take effect, you agree to the updated Terms.",
    ],
  },
  {
    id: "law",
    title: "14. Governing law",
    paragraphs: [
      "These Terms are governed by the laws of the United Kingdom.",
      "Any disputes relating to these Terms or your use of Grant will be subject to the applicable courts of the United Kingdom.",
    ],
  },
  {
    id: "contact",
    title: "15. Contact",
    paragraphs: [
      "If you have questions about these Terms, contact:",
    ],
    note: contactEmail,
  },
];

export function TermsPageView() {
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => {
    function onScroll() {
      setScrolled(window.scrollY > 20);
    }

    onScroll();
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  return (
    <div className="min-h-screen bg-[var(--creed-background)] text-[var(--creed-text-primary)]">
      <MarketingHeroBanner configured scrolled={scrolled} />

      <main className="mx-auto max-w-3xl px-6 pb-20 pt-8 md:px-10 md:pb-24 md:pt-10">
        <div className="border-b border-[var(--creed-border)] pb-8">
          <AnimatedPageTitle text="Terms and Conditions" />
          <p className="t-lede mt-5 max-w-2xl text-[var(--creed-text-secondary)]">
            The rules that govern your use of Grant.
          </p>
        </div>

        <div className="border-b border-[var(--creed-border)] pb-8 pt-8 text-[var(--creed-text-secondary)]">
          <div className="space-y-4 text-[16px] leading-8 md:text-[17px]">
            {introParagraphs.map((paragraph) => (
              <p key={paragraph}>{paragraph}</p>
            ))}
          </div>
        </div>

        <div className="pt-2">
          {sections.map((section) => (
            <section
              key={section.id}
              id={section.id}
              className={section.id === "contact" ? "py-8 md:py-10" : "border-b border-[var(--creed-border)] py-8 md:py-10"}
            >
              <AnimatedSectionHeading text={section.title} className="t-step" />

              <div className="mt-5 space-y-4 text-[15px] leading-8 text-[var(--creed-text-secondary)] md:text-[16px]">
                {section.paragraphs?.map((paragraph) => (
                  <p key={paragraph}>{paragraph}</p>
                ))}
              </div>

              {section.bullets ? (
                <ol className="mt-5 list-decimal space-y-3 pl-5 text-[15px] leading-8 text-[var(--creed-text-secondary)] marker:font-medium marker:text-[var(--creed-accent)] md:text-[16px]">
                  {section.bullets.map((item) => (
                    <li key={item} className="pl-1 first-letter:uppercase">{item}</li>
                  ))}
                </ol>
              ) : null}

              {section.note ? (
                section.id === "contact" && CONTACT_EMAIL ? (
                  <a
                    href={`mailto:${CONTACT_EMAIL}`}
                    className="mt-5 inline-block font-medium text-[15px] leading-8 text-[var(--creed-accent)] transition-colors hover:text-[var(--creed-accent-hover)] md:text-[16px]"
                  >
                    {section.note}
                  </a>
                ) : (
                  <p className="mt-5 text-[15px] leading-8 text-[var(--creed-text-primary)] md:text-[16px]">
                    {section.note}
                  </p>
                )
              ) : null}
            </section>
          ))}
        </div>
      </main>

      <MarketingFooter />
    </div>
  );
}
